version: '3.8'

services:
  explorer:
    image: "node:8"
    container_name: explorer
    user: "0:0"
    working_dir: /home/node/app
    volumes:
      - ".:/home/node/app"
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: "bash docker-ops.sh start "
  postgresql:
    image: ubuntu/postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_DATABASE=telescope
      - POSTGRESQL_USER=telescope
      - POSTGRESQL_PASSWORD= "123456"
    volumes:
      - "../data:/var/lib/pgsql/data"
      - "./app/persistence/postgreSQL/db/:/opt/app-root/src"
      - "/root/.telescope/pg_data"


networks:
  bridge-network:
    driver: bridge
